version: "3.5"

volumes:
    data:

networks:
    study_network:
        name: study_network
        driver: bridge

services:
    backend:
        build: .
        container_name: study_backend
        restart: always
        ports:
            - 80:80
        networks:
            - study_network
        image: study_backend